#!/bin/sh
# By chris1111
#

. /etc/rc.common

echo "PostInstall_UI.command"
Sleep 2
ditto -x -k --sequesterRsrc --rsrc /Private/tmp/StatusBarApp.zip "/Library/Application Support/WLAN/"
cp -rp /Private/tmp/RtWlanHelper "/Library/Application Support/WLAN/"
rm -rf /Private/tmp/StatusBarApp.zip
rm -rf /Private/tmp/RtWlanHelper
Sleep 1


#Filename of Application.
APP="StatusBarApp"
HELPER="RtWlanHelper"
INF_NAME="netrtwlanu.inf"
AUX_PATH="com.realtek.utility.wifi"


#APP location.
ROOT_PATH="/Library/Application Support/WLAN"
AUX_PATH="com.realtek.utility.wifi"
UTILITY_SOCK_NAME="/var/tmp/com.realtek.utility.statusbar.socket"


sudo chmod -R 777 "$ROOT_PATH/$APP.app"
sudo chmod -R 777 "$ROOT_PATH/$AUX_PATH/"
sleep 1
sudo chown -R root:wheel "$ROOT_PATH/$APP.app"
sudo chown -R root:wheel "$ROOT_PATH/$HELPER"


# chmod 777 is not work.
# [MACOS-15]
chmod -R 777 $UTILITY_SOCK_NAME



Sleep 2
open "/Library/Application Support/WLAN/StatusBarApp.app"
echo "Done"
Sleep 2
osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Library/Application Support/WLAN/StatusBarApp.app", hidden:false}'

echo "PostInstall_UI Complete."

